// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCrErIL4D3JdZ7pTX1m1kbwCn5BjkjP7c',
    appId: '1:1063055591945:android:6f5f034505ec5105cb46d8',
    messagingSenderId: '1063055591945',
    projectId: 'p30nailbook',
    storageBucket: 'p30nailbook.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg9cpCMW93aBcb7K4WAIs-NwQ_pj59nNA',
    appId: '1:1063055591945:ios:f6f0189dc4fa2f18cb46d8',
    messagingSenderId: '1063055591945',
    projectId: 'p30nailbook',
    storageBucket: 'p30nailbook.appspot.com',
    androidClientId: '1063055591945-18s8js1h72ptoo6ev8uk5pgakjp8qu3q.apps.googleusercontent.com',
    iosClientId: '1063055591945-h11nrpljteh9q79fg9btmanr77o7m93a.apps.googleusercontent.com',
    iosBundleId: 'io.izisoft.p30nailsupply',
  );
}
